# Generated by Django 4.2.26 on 2025-12-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Tree Planting', 'Tree Planting'), ('Recycling', 'Recycling'), ('Cleanup', 'Cleanup'), ('Awareness', 'Awareness'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
