# Generated by Django 4.2.26 on 2025-12-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
