# Generated by Django 4.2.26 on 2025-12-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_is_organizer_profile_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured to show on homepage (staff only)'),
        ),
    ]
